server:
  port: 8080
spring:
  application:
    name: finance-api
  datasource:
    url: ${DATABASE_URL}
    username: ${USERNAME}
    password: ${PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
